name = "Dystopia_SMP_Project"
author = "RubleDruble"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2f435691989a53e26c52e5789eed356cce5d27b6424a8149dd03dfeda35fdeeb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"
