name = "Dystopia_SMP_Project"
author = "RubleDruble"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9ec0a4b6bae1e27b38c02048c9b9e49a6cac8ace16532fdc37b4da07dad2d199"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"
