name = "Dystopia_SMP_Project"
author = "RubleDruble"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2544e58dcaa3861ebd8cafe288b1dcf9cc9cc8a0232f699cbb9f49497845e516"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"
