name: Build and Release Dystopia SMP Modpack

on:
  push:
    branches: 
        - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Install packwiz
        run: go install github.com/packwiz/packwiz@latest

      - name: Export Modrinth Pack (.mrpack)
        run: ~/go/bin/packwiz modrinth export --output neoforge-pack.mrpack

      - name: Rename file to .zip for Prism
        run: mv neoforge-pack.mrpack Dystopia_SMP_Modpack.zip

      - name: Calculate Version Number
        run: |
          # Subtracts 5 from the build number safely using bash arithmetic
          VERSION_OFFSET=$(( ${{ github.run_number }} - 5 ))
          echo "PACK_VERSION=1.0.$VERSION_OFFSET" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "${{ env.PACK_VERSION }}"
          name: "Modpack Release ${{ env.PACK_VERSION }}"
          files: Dystopia_SMP_Modpack.zip
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}